rpc-state-reader/src/blockifier_state_reader.rs

Sierra contract classes are needed to run contract entrypoints using cairo-native. This PR changes the method `get_compiled_contract_class` to return sierra contract classes instead of compiling them to casm contract classes

Return sierra contract class  in `RpcStateReader:: get_compiled_contract_class`

---

Cargo.lock
rpc-state-reader/Cargo.toml

This fixes failing tx 0x41497e62fb6798ff66e4ad736121c0164cdb74005aa5dab025be3d90ad4ba06

Bump blockifier version to include latest bugfix

---

Cargo.lock
rpc-state-reader/Cargo.toml
rpc-state-reader/src/blockifier_state_reader.rs

Based on #6 
* Checks internal transaction data (CallInfo) against mainnet data fetched from RPC)
* Removes fee checks from tests (as they are currently failing due to differences in resource count)
* Merges tests cases into a single test (as we are not comparing against another starknet implementation)
* Removes `todo!()` from code
* Reverts the charge_fee change so we can run the tests (The TODO comment is still there)

Improve testing

---

replay/src/main.rs
rpc-state-reader/src/blockifier_state_reader.rs

The current implementation executes each transactions in a block individually with the state from the previous block (n-1). This breaks when transaction on the same block depend on themselves.
1. An account is deployed
2. The account sends an invoke transaction
If you execute 2. without executing 1., then in your internal state the account won't exist yet, so the transaction will fail. The solution is to persist the state changes between executions of transaction on the same block.
With the changes introduced in this PR some changes must be made to keep consistency, i.e: `execute_tx_configurable_with_state` originally was the only function that received state but now all of them do, so the function probably doesn't make sense anymore. I think this should be addressed in another PR to keep …

fix: Persist cached state

---

Cargo.toml
README.md
replay/Cargo.toml
replay/src/main.rs

Adds tracing logging to the replay binary. The logs have the following structure:
- A block span for all transactions in a given block
- A transaction span for the execution of a single transaction
- An error event is emitted if the status of the RPC and the blockifier execution don't match, or if the transaction fails unexpectedly
- An info event is emitted if the status matches

Add tracing logging

---

.github/workflows/ci.yml
Cargo.lock
replay/Cargo.toml
replay/src/main.rs
rpc-state-reader/Cargo.toml
rpc-state-reader/src/blockifier_state_reader.rs
rpc-state-reader/src/rpc_state.rs

Adds CI workflow
- Corrects code to make CI pass
- Adds more tests
Should be merged after #16 as it was developed from that branch
The `--all-features` flag was deliberately left out of the CI as the benchmark feature it's currently being worked on in #13  (and it does not compile in main). Before merging that PR, it must be added to the CI

Add actions

---

Cargo.lock
Cargo.toml
rpc-state-reader/Cargo.toml

* Update blockifier version so that we can use the last version of cairo_native
* Update cairo-lang version to 2.6.3

Update blockifier and cairo-lang version

---

rpc-state-reader/src/blockifier_state_reader.rs

Changes the tests so that they have the current transaction block in the test case, instead of the previous one

Use tx current block in tests

---

.github/workflows/ci.yml
Cargo.lock
replay/src/benchmark.rs
replay/src/main.rs
rpc-state-reader/Cargo.toml
rpc-state-reader/src/blockifier_state_reader.rs
rpc-state-reader/src/rpc_state.rs

Adds `BenchBlockRange` Command to Replay crate under the Benchmark features.
The command is used to measure the performance of Cairo Native without the overhead of rpc requests. Caching native compilation is not yet possible in the current blockifier version
Supersedes #12
The bench block range command has roughly three distinct steps:
1. Fetch all block range data, this includes all transactions and block context information needed to execute them
2. Executes the whole block range once, to make sure all internal data required by blockifier is cached
3. Executes (and measures) the whole block range `n` times. This third step won't make any rpc call as all data has already been cached.
The benchmark command ended up being quite lengthy, so I left the high level command implementation in …

Benchmark feature

---

.gitignore
Makefile
README.md
env.sh

- Adds makefile with common commands
- Adds env.sh script to set up environment variables.
- Updates README.md to document Makefile commands and env.sh
The --all-features flag was deliberately left out of the make rules as the benchmark feature it's currently being worked on in https://github.com/lambdaclass/starknet-replay/pull/13 (and it does not compile in main). Before merging that PR, it must be added to the Makefile.
I left out some Makefile rules to keep it simple, but I can add them if they are desired:
- `make runtime`: Clones cairo native and compiles the runtime library
- `make check-env`: Checks that all needed env variables are set. If I add this then there is probably no need for printing a remainder in `env.sh`

Adds Makefile and env.sh

---

Cargo.lock
Cargo.toml
replay/Cargo.toml
rpc-state-reader/Cargo.toml
rpc-state-reader/src/blockifier_state_reader.rs

Add the only_cairo_vm feature to the replay crate. This feature is designed to avoid executing transitions with cairo_native and instead use cairo_vm exclusively. It is useful for testing, comparing results, and benchmarking.
To support this, we also introduce the only_casm feature in the rpc_state_reader crate.

Add the only_cairo_vm feature

---

replay/src/main.rs
rpc-state-reader/src/blockifier_state_reader.rs

Refers to: #34 
This PR adds tests checking some `TransactionInfo` fileds:
- `da_gas`
- `state_changes_for_fee`
- `actual_resources.starknet_resources`
- `revert_error`

Add TransactionInfo tets

---

replay/src/benchmark.rs
replay/src/main.rs

Times the execution of each transactions in the `bench-block-range` command, and changes the log subscriber to use json format (only with benchmark feature):
```json
{"timestamp":"2024-08-12T18:31:46.409997Z","level":"INFO","fields":{"message":"fetching block range data"},"target":"replay","span":{"name":"caching block range"},"spans":[{"name":"caching block range"}]}
{"timestamp":"2024-08-12T18:34:49.390927Z","level":"INFO","fields":{"message":"filling up execution cache"},"target":"replay","span":{"name":"caching block range"},"spans":[{"name":"caching block range"}]}
{"timestamp":"2024-08-12T18:34:49.391127Z","level":"INFO","fields":{"message":"starting block execution"},"target":"replay::benchmark","span":{"block_number":630029,"name":"block execution"},"spans":[{"name":"caching block …
```

Add timers to benchmark feature

---

Makefile

When we added the Makefile, we intentionally left out the all-features flag because the benchmark feature didn't compile. Now the benchmark feature works correctly, so we can add the flag to the makefile.

Add all-features to Makefile

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
replay/src/main.rs
rpc-state-reader/Cargo.toml
rpc-state-reader/src/blockifier_state_reader.rs
rpc-state-reader/src/lib.rs
rpc-state-reader/src/rpc_state.rs
rust-toolchain.toml

This PR changes the dependency blockifier to point to: https://github.com/lambdaclass/sequencer/tree/native2.8.x-arc/crates/blockifier. I created a new branch [native2.8.x-arc](https://github.com/lambdaclass/sequencer/compare/native2.7.x...lambdaclass:sequencer:native2.8.x-arc) that uses Cairo 2.8 and `Arc<AotNativeExecutor>`.
This PR continued upon #45, so we can close that one and merge this one instead.

Update blockifier to sequencer

---

replay/src/main.rs
rpc-state-reader/src/rpc_state.rs

This PR adds the resources, events and messages used during transactions to the logs. It adds: 
1. The amounts of l2 to l1 messages and events that happened during the transaction.
2. The data availability gas consumed.
3. The state changed that happend: `n_class_hash_updates`, `n_compiled_class_hash_updates` ,`n_modified_contracts`, `n_storage_updates`.
The only ones that can be matched with the rpc are the events and the messages since those are returned by the rpc.
Currently, the blockifier is not counting the event's number correctly (or that's what I'm supposing) since they differ in 1 with the rpc result. My guess is that this due to an error in the implementation which only takes into account the events produced by the inner_calls and does not count the ones generated by the …

Add extra info to transactions logs

---

replay/src/main.rs

This PR adds the root of the error, if it was the case. It could be because the execution status diverged or the events and messages count. Due to this, it shows which one of the four ( there could be a case where both events and messages count fail) has happend, having more precedence the execution status error.

Add error reason to the logs

---

.gitignore
Cargo.lock
Cargo.toml
rpc-state-reader/src/utils.rs
rust-toolchain.toml

Uses new ContractExecutor instead of AotExecutor. Now it saves compiled contracts to disk so they can be reutilized on later runs.
It also changes sequencer branch to `native2.8.x`, unifying all other branches.

Use Contract Executor

---

Cargo.toml

Changes single quotes to double quotes. Since we are mostly using double quotes, I changed it to prevent incompatibilities when patching the cairo_native's version during the blocks running in the ci.

change quotes

---

scripts/delta_state_dumps.sh

Closes #70
Removes the `U` flag, as it doesn't work in Linux.

Fix cmp order of `delta_state_dumps.sh`

---

replay/src/main.rs

Closes #72
This PR writes the execution error to the state dump if it fails to complete. For example, the following command:
```bash
cargo run --features state_dump,only_cairo_vm tx 0x01438d65c0b7f923b9cd40b52341b99c1061ac5dc0ab97720d798b8d0ce0f882 mainnet 724000
```
Will generate the following file:
```bash
> cat state_dumps/vm/block724000/0x01438d65c0b7f923b9cd40b52341b99c1061ac5dc0ab97720d798b8d0ce0f882.json 
"Invalid transaction nonce of contract at address 0x066be86a31e7a708e17a2f813073fd489f661cf6fa4d949d2c3c8d59e7003a74. Account nonce: 0x00000000000000000000000000000000000000000000000000000000000000db; got: 0x00000000000000000000000000000000000000000000000000000000000000dc."⏎ 
```
Rather than generating nothing

Dump state also on error

---

replay/src/main.rs
replay/src/state_dump.rs

This PR fixes two bugs:
- If the parent dir of a state dump didn't exist, then the execution would panic when trying to write it.
- The file format was not a JSON, and cause diffs due to the fact that Cairo Native and Cairo VM have different error formats.

Fix bug on Error State Dump

---

.gitignore
Cargo.lock
Cargo.toml
README.md
plotting/plot_execution_time.py
plotting/utils.py
replay/Cargo.toml
replay/src/benchmark.rs
replay/src/main.rs
rpc-state-reader/src/execution.rs
scripts/benchmark_block.sh
scripts/benchmark_tx.sh

Depends on https://github.com/lambdaclass/sequencer/pull/25
Instead of relying on logs, it saves important execution info to a file post-benchmarks, which can be later processed with a different tool (i.e Python)
This PR also updates the `plot_execution_time` python script to read from this file.

Save contract execution time

---

Cargo.lock
replay/src/benchmark.rs
replay/src/main.rs
rpc-state-reader/Cargo.toml
rpc-state-reader/src/cache.rs
rpc-state-reader/src/execution.rs
rpc-state-reader/src/lib.rs
rpc-state-reader/src/objects.rs
rpc-state-reader/src/reader.rs

Adds cache to RPC calls.
Depends on #107
- Defines a new structure `RpcCachedStateReader` that wraps around `RpcStateReader` and caches each RPC call made. On drop, the whole cache is stored on disk.
- Also defines a new trait `StateReader` that both the cache and non-cache readers implement. Some `RpcStateReader` methods were moved to this trait.
- By default, the execution functions don't use the cache. I added a new function `fetch_transaction_with_state` that receives a custom reader, and thus can use `RpcCachedStateReader`.
- The cached data is stored in the `rpc_cache` directory, with a single file for each block.
Note: Only a single instance of replay should run at a time, to avoid race conditions.
- In addition to RPC calls, the `RpcStateReader` had additional logic for deriving …

Add cache to RPC Calls

---

Cargo.lock
Cargo.toml
rpc-state-reader/Cargo.toml
rpc-state-reader/src/cache.rs

Currently, if two replay instances execute the same block at the same time, race conditions can appear when writing to the cache, corrupting it's state.
This PR fixes it by using file locks to ensure that only one process modifies the cache at a time.
I added fs2 as a dependency, as the file lock API of the standard fs crate is nightly only.

Add locking to avoid race conditions in cache

---

rpc-state-reader/src/reader.rs
rpc-state-reader/src/utils.rs

This PR saves compiled CASM contracts to disk, making VM reexecution faster.
The cached contracts are stored at `compiled_programs/<hash>.casm.json`
As a test, I executed with the VM transaction `0x59bfd720bb72b1063ee3f0c3864019a008a22ef662e5f907012b0e9800f78f0`:
- First execution (no CASM cache): 37.33 seconds
- Second execution (with CASM cache): 16.50 seconds

Add CASM cache

---

rpc-state-reader/src/utils.rs

We have a bug in the CASM cache, causing the CI to fail due to race conditions.
This PR reverts it so that we can have the CI working again. Later, we can reimplement the CASM cache correctly.

Revert CASM cache

---

Makefile
README.md

This PR documents the need of removing compiled_programs directory when updating Cairo Native.
Closes #93

Document compiled_programs removal

---

Cargo.lock
Cargo.toml
replay/src/benchmark.rs
replay/src/main.rs
rpc-state-reader/src/execution.rs
rpc-state-reader/src/lib.rs
rpc-state-reader/src/reader.rs

Depends on https://github.com/lambdaclass/sequencer/pull/44
Some transactions reverted due to invalid account signature, both in Native and VM.
This PR changes two things that fixed the issue:
- Using sequencer's ChainId, rather than our RpcChain
- Using the appropiate versioned contants, according to the transactions starknet version, rather than using always the latest ones.

Fix invalid account signature

---

rpc-state-reader/src/cache.rs

Writes cache without pretty print to save disk usage

Don't write cache as pretty json

---

README.md
replay/src/main.rs

Adds a new command `block-txs` that executes a given set of transaction from within a block.
Its useful when need to reexecute a single transaction, which depend on other transaction on the same block. If we know the dependencies, we can execute only the neccessary transactions, instead of execution the whole block (which may be very large).

Add block-txs command

---

Cargo.lock
Cargo.toml
rpc-state-reader/Cargo.toml

Bump Cairo to v2.11.2
- Also update the sequencer dependency to use latest upstream changes.

Bump Cairo to v2.11.2

---

replay/src/benchmark.rs
rpc-state-reader/src/objects.rs

Some minor fixes:
- We used to assert that the call info didn't have a time `0`. Turns out that its possible for some call infos to contain the default value. For example, executing an empty constructor: https://github.com/lambdaclass/sequencer/blob/7e7f34e756edcb1f3334aabcc0f8ec3dce40c85a/crates/blockifier/src/execution/entry_point.rs#L436
- Some of the new blocks have the `l1_data_gas` field now. This PR adds support for it, as it used to fail at deserialization.

Fix some bugs
